name: Build ESP32 Firmware

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install ESP-IDF
      - name: Install ESP-IDF
        run: |
          git clone -b v5.5.3 --recursive https://github.com/espressif/esp-idf.git esp-idf
          cd esp-idf
          ./install.sh

      # Set up ESP-IDF environment
      - name: Export ESP-IDF variables
        run: |
          cd $GITHUB_WORKSPACE
          . esp-idf/export.sh

      # Install dependencies via IDF component manager
      - name: Add dependencies
        run: |
          cd $GITHUB_WORKSPACE
          . esp-idf/export.sh
          idf.py set-target esp32
          idf.py add-dependency "espressif/esp-dsp^1.7.0"
          idf.py add-dependency "espressif/esp-sr^2.3.1"

      # Build firmware
      - name: Build firmware
        run: |
          cd $GITHUB_WORKSPACE
          . esp-idf/export.sh
          idf.py build

      # Upload firmware artifact
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware
          path: build/
