name: Build ESP32 Firmware

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install latest CMake for ESP-IDF
      - name: Install CMake
        run: |
          sudo apt update
          sudo apt remove --purge cmake -y
          sudo apt install -y wget build-essential
          wget https://github.com/Kitware/CMake/releases/download/v3.27.5/cmake-3.27.5-linux-x86_64.sh
          chmod +x cmake-3.27.5-linux-x86_64.sh
          sudo ./cmake-3.27.5-linux-x86_64.sh --skip-license --prefix=/usr/local
          cmake --version

      # Install ESP-IDF
      - name: Install ESP-IDF
        run: |
          git clone -b v5.5.3 --recursive https://github.com/espressif/esp-idf.git esp-idf
          cd esp-idf
          ./install.sh

      # Cache ESP-IDF components
      - name: Cache ESP-IDF
        uses: actions/cache@v3
        with:
          path: esp-idf
          key: ${{ runner.os }}-esp-idf-${{ hashFiles('**/sdkconfig') }}
          restore-keys: |
            ${{ runner.os }}-esp-idf-

      # Cache build folder
      - name: Cache build folder
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.c','**/*.h') }}
          restore-keys: |
            ${{ runner.os }}-build-

      # Build firmware
      - name: Build firmware
        run: |
          cd $GITHUB_WORKSPACE
          . esp-idf/export.sh
          idf.py set-target esp32
          idf.py add-dependency "espressif/esp-dsp^1.7.0"
          idf.py add-dependency "espressif/esp-sr^2.3.1"
          idf.py build

      # Upload firmware artifact
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware
          path: build/
